export type Enrollment = {
  enrollmentId: number;
  courseId: number;
  studentId: number;
  studentNumber: number;
  tutorId: number | null;
  maxAssignments: number | null;
  graduated: boolean;
  assignmentsDisabled: boolean;
  quizzesDisabled: boolean;
  onHold: boolean;
  holdReason: string | null;
  currencyCode: string;
  courseCost: number;
  amountPaid: number;
  monthlyInstallment: number | null;
  enrollmentDate: Date | null;
  dueDate: Date | null;
  fastTrack: boolean;
  paymentsDisabled: boolean;
};

export type RawEnrollment = {
  enrollmentId: number;
  courseId: number;
  studentId: number;
  studentNumber: number;
  tutorId: number | null;
  maxAssignments: number | null;
  graduated: boolean;
  assignmentsDisabled: boolean;
  quizzesDisabled: boolean;
  onHold: boolean;
  holdReason: string | null;
  currencyCode: string;
  courseCost: number;
  amountPaid: number;
  monthlyInstallment: number | null;
  enrollmentDate: string | null;
  dueDate: string | null;
  fastTrack: boolean;
  paymentsDisabled: boolean;
};
